version: '3'
services:
  migration:
    image: boxfuse/flyway:latest
    container_name: flyway_migration
    volumes:
     - ./sql:/flyway/sql
     - ./bin:/flyway/bin
    entrypoint: ["bash", "/flyway/bin/wait-for-it.sh", "--timeout=30", "db:1433", "--", "flyway"]      
    command: -url=jdbc:sqlserver://db;database=master -user=sa -password=yourStrongPassw0rd! -mixed=true -target=1.1 migrate 
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "yourStrongPassw0rd!"
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "true"
    ports:
      - "1433:1433"